pipeline {

   agent any

   environment {
    ANSIBLE_CONFIG='${WORKSPACE}Project-14_main/ansible-config-mgt/deploy/ansible.cfg'
   }

  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
  }

   stages {

    stage('Initial Clean Up') {
      steps {
        dir('${WORKSPACE}') {
         deleteDir()
        }

      }
    }

    stage('Checkout SCM') {
      steps {
        git branch: 'main', url: 'https://github.com/AbisolaQ/Project-14/tree/main/ansible-config-mgt'
      }
    }

    stage('Setting Roles Path in the Ansible.cfg File') {

      steps {
        sh 'echo ${WORKSPACE}'
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}Project-14_main/ansible-config-mgt/deploy/ansible.cfg'
      }
    }

    stage('Run Ansible Playbook') {

      steps {
        ansiblePlaybook become: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbook/site.yml'

      }
    }

    stage('Clean Up') {
      steps {
         cleanWs(cleanWhenAborted: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, cleanWhenFailure: true)
      }

    }
     
   }
}


